using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace WEI
{
    /// <summary>
    /// ĻÔł‹ģōįĽīķ®t≤ő
    /// </summary>
    public class SystemDetectConversation : MonoBehaviour
    {
        public GameObject button;
        public GameObject talkUI;

        private void OnTriggerEnter(Collider other)
        {
            //Debug.Log("∂i§JįŌįž");
            button.SetActive(true);
        }
        private void OnTriggerExit(Collider other)
        {
            //Debug.Log("®S¶≥∂i§JįŌįž");
            button.SetActive(false);
        }
        private void Update()
        {
            if (button.activeSelf && Input.GetKeyDown(KeyCode.R))
            {
                talkUI.SetActive(true);
            }
        }
    }
}
